version: '2'
services:
  web:
    build: .
    container_name: ingest-app
    volumes:
      - './sites.json:/config/parsed.json'
    ports:
      - 8080:8080
    depends_on:
      - "sample"
      - "mongodb"
    environment:
      - SERVER=mongodb
      - DB=article
      - ARTICLE_COLLECTION=articles
      - DB_USER=article_user
      - DB_PASSWORD=article123
      - CONFIG_FILE=/config/parsed.json
      - SOURCES=http://sample-webpage?instance=1,http://sample-webpage?instance=2
      - AUTH_DB=article
      - DB_SSL=false

  sample:
    image: httpd:latest
    container_name: sample-webpage
    ports:
      - 8081:80
    volumes:
      - .:/usr/local/apache2/htdocs

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - NODE_ENV=production
      - MONGO_INITDB_ROOT_USERNAME=root_username
      - MONGO_INITDB_ROOT_PASSWORD=very_secure_root_pass
    volumes:
      - ./data/db:/data/db
      - "./mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    ports:
        - 27017:27017
