# Deps

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.5.0"

[prune]
  go-tests = true
  unused-packages = true
  
[[constraint]]
  name = "github.com/mongodb/mongo-go-driver"
  version = "0.1.0"
