apiVersion: v1
kind: ConfigMap
data:
  server: "{{ .Values.server }}"
  db: "{{ .Values.db }}"
  articleCollection: "{{ .Values.articleCollection }}"
  dbUser: "{{ .Values.dbUser }}"
  dbPassword: "{{ .Values.dbPassword }}"
  authDb: "{{ .Values.authDb }}"
  dbSsl: "{{ .Values.dbSsl }}"
  configFileLocation: "{{ .Values.configFileLocation }}"
metadata:
  name: {{ .Release.Name }}-configmap
