apiVersion: v1
kind: ConfigMap
data:
  port: "{{ .Values.port }}"
  server: "{{ .Values.server }}"
  db: "{{ .Values.db }}"
  articleCollection: "{{ .Values.articleCollection }}"
  dbUser: "{{ .Values.dbUser }}"
  dbPassword: "{{ .Values.dbPassword }}"
  authDb: "{{ .Values.authDb }}"
  dbSsl: "{{ .Values.dbSsl }}"
metadata:
  name: {{ .Release.Name }}-configmap
