apiVersion: v1
kind: ConfigMap
data:
  dbSsl: "{{ .Values.dbSsl }}"
  configFileLocation: "{{ .Values.configFileLocation }}"
  sources: "{{ .Values.sources }}"
metadata:
  name: {{ .Release.Name }}-configmap
