apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  username: {{ .Values.dbUser }}
  password: {{ .Values.dbPassword }}
  db: {{ .Values.db }}
  collection: {{ .Values.articleCollection }}
  server: {{ .Values.server }}
  authdb: {{ .Values.authDb }}
