apiVersion: v1
kind: Service
metadata:
  name: {{ include "article-ingest.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "article-ingest.name" . }}
    helm.sh/chart: {{ include "article-ingest.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 2112
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "article-ingest.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
