version: 2
jobs:
  build:
    docker:
       - image: google/cloud-sdk
    steps:
      - checkout
      - run: chmod +x ./deployment/build.sh
      - run: bash ./deployment/build.sh
      - persist_to_workspace:
        root: .
        paths:
          - docker-cache
  tag:
    machine: true
    steps:
      - checkout
      - attach_workspace:          
        at: . 
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker load --input docker-cache/built-image.tar
      - run: docker push $DOCKER_IMAGE_URL:$CIRCLE_SHA1
  test:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/tommbee/go-article-ingest
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure
      - run: go get
      - run: go test
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: chmod +x ./deployment/deploy.sh
      - run: bash ./deployment/deploy.sh
workflows:
  version: 2
  untagged-build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore: master
      - test:
          requires:
            - build
  tagged-build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
      - tag:
          requires:
            - build
      - test:
          requires:
            - tag
      - hold:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - hold
