version: 2
jobs:
  build:
    docker:
       - image: docker
    steps:
      - checkout
      - run: chmod +x ./deployment/build.sh
      - run: bash ./deployment/build.sh
  test:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/tommbee/go-article-ingest
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure
      - run: go get
      - run: go test
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: chmod +x ./deployment/deploy.sh
      - run: bash ./deployment/deploy.sh
workflows:
  version: 2
  untagged-build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore: master
      - test:
          requires:
            - build
  tagged-build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - hold
