version: 2

references:

jobs:
  ## Compile the app
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: chmod +x ./deployment/build.sh
      - run: bash ./deployment/build.sh
      - persist_to_workspace:
          root: .
          paths:
            - site-config
            - kubeconfig
  ## Push to the docker repo
  tag:
    machine: true
    steps:
      - checkout
      - attach_workspace:          
          at: . 
      - run: cp site-config/${CONFIG_FILENAME} ./${CONFIG_FILENAME}
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build --build-arg CONFIG_FILENAME=${CONFIG_FILENAME} -t $DOCKER_IMAGE_URL:$CIRCLE_SHA1 .
      - run: docker push $DOCKER_IMAGE_URL:$CIRCLE_SHA1
  ## Run unit tests
  test:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/tommbee/go-article-ingest
    steps:
      - checkout
      - attach_workspace:          
          at: . 
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure
      - run: go get
      - run: go test
  ## Deploy app to cluster using helm
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: cp site-config/${CONFIG_FILENAME} ./deployment/${CONFIG_FILENAME}
      - run: cp site-config/${CONFIG_FILENAME} ./${CONFIG_FILENAME}
      - run: chmod +x ./deployment/deploy.sh
      - run: bash ./deployment/deploy.sh

workflows:

  version: 2
  untagged-build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore: master
      - test:
          requires:
            - build
  tagged-build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
      - tag:
          requires:
            - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - tag
            - test
      - deploy:
          requires:
            - hold
