variable "client_certificate" {}
variable "client_key" {}
variable "cluster_ca_certificate" {}
variable "host" {}
variable "token" {}

## app specific
variable "image_repository" {}
variable "image_tag" {}
variable "sources" {}
variable "server" {}
variable "db" {}
variable "config_file_location" {}
variable "article_collection" {}
variable "db_user" {}
variable "db_password" {}
variable "auth_db" {}
variable "db_ssl" {}
variable "namespace" {}
